tap "oven-sh/bun", trusted: true
tap "teamookla/speedtest", trusted: true

brew "btop"
brew "coreutils"
brew "fnm"
brew "gh"
brew "git"
brew "gnupg"
brew "htop"
brew "jq"
brew "kubo"
brew "oven-sh/bun/bun"
brew "pinentry-mac"
brew "pure"
brew "railway"
brew "rclone"
brew "rsync"
brew "scw"
brew "shellcheck"
brew "teamookla/speedtest/speedtest"
brew "tor"
brew "wget"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "claude-code@latest"
cask "codex"
