#!/bin/bash

# Install Homebrew
ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install what we need
brew install git
brew install node --without-npm
brew install wget
brew install gpg2
brew install mysql
brew install imagemagick
brew install GraphicsMagick
brew install android

# Install npm on its own
curl -L https://npmjs.org/install.sh | sh