#!/bin/bash

# Installed from brewfile with node

# install global stuff
npm install -g bower
npm install -g grunt-cli
npm install -g gulp
# Install Keybase
# https://keybase.io/docs/command_line/installation
npm install -g keybase-installer
keybase-installer