#!/bin/bash

# Installed from brewfile with node

# install global stuff
npm install -g bower grunt grunt-cli gulp

# Install Keybase
# https://keybase.io/docs/command_line/installation
npm install -g keybase-installer
keybase-installer