set -g default-terminal "tmux-256color"
set -g history-limit 10000
set -s escape-time 0

# Mouse support — click panes, resize, scroll
set -g mouse on

# Allow default copy and pasting behaviour
set -s set-clipboard external

# Window and pane numbering
set -g base-index 1
set -g renumber-windows on

# enable activity alerts
setw -g monitor-activity on
set -g visual-activity on

set -g display-time 1000
set -g status-interval 10

set-option -g status-position bottom
